server:
  port: 9099
spring:
  flyway:
    enabled: true
    encoding: utf-8
    locations: classpath:db_sql
    validate-on-migrate: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:sqlite:games.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      data-source-properties:
        # 支持多线程操作
        journal_mode: wal
        synchronous: off
        date_string_format: "yyyy-MM-dd HH:mm:ss"
        busy_timeout: 30000
        transaction_mode: IMMEDIATE
      minimum-idle: 2
      maximum-pool-size: 10
  application:
    name: game-service

mybatis-plus:
  configuration:
    database-id: SQLITE
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: session
    default-statement-timeout: 25000
    cache-enabled: true
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    safe-row-bounds-enabled: false
  mapper-locations:
    - classpath*:/repository/**/*.xml
  global-config:
    db-config:
      table-prefix: t_
logging:
  level:
    com.pettyfox.*: debug